version: '3.7'

services:
    postgresql:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: ${PG_PASS}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_DB: ${PG_DB}
        volumes:
            - /var/cache/pgdata:/var/lib/postgresql/data

    users_app:
        image: romaiolima/apiusers:1.0
        build: .
        entrypoint: ./entrypoint.sh
        ports:
            - "8000:8000"
        depends_on:
            - postgresql
        environment:
            - DATABASE_URL=postgresql+asyncpg://admin:admin@postgresql:5432/fastapi
            - DATABASE_URL_ALEMBIC=postgresql+psycopg2://admin:admin@postgresql:5432/fastapi
    
