version: '3.1'

services:
    postgresql:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: ${PG_PASS}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_DB: ${PG_DB}
        volumes:
            - /var/cache/pgdata:/var/lib/postgresql/data
